INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('2001-11-23 ', 'john@gmail.com', 'John', 'Doe');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('1995-04-15 ', 'jane@gmail.com', 'Jane', 'Smith');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('1980-08-10 ', 'bob@gmail.com', 'Bob', 'Johnson');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('1992-03-28 ', 'susan@gmail.com', 'Susan', 'Williams');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('2002-09-12 ', 'mike@gmail.com', 'Mike', 'Brown');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('1998-06-17 ', 'lisa@gmail.com', 'Lisa', 'Davis');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('1987-12-05 ', 'david@gmail.com', 'David', 'Miller');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('2000-02-20 ', 'emily@gmail.com', 'Emily', 'Wilson');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('1983-01-08 ', 'mark@gmail.com', 'Mark', 'Moore');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('1990-07-30 ', 'sarah@gmail.com', 'Sarah', 'Taylor');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('2003-10-25 ', 'peter@gmail.com', 'Peter', 'Anderson');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('1985-05-03 ', 'laura@gmail.com', 'Laura', 'White');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('1993-09-19 ', 'kevin@gmail.com', 'Kevin', 'Martinez');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('2002-07-14 ', 'jennifer@gmail.com', 'Jennifer', 'Lee');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('1988-04-01 ', 'michael@gmail.com', 'Michael', 'Harris');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('1997-11-09 ', 'amanda@gmail.com', 'Amanda', 'Clark');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('1986-03-12 ', 'steven@gmail.com', 'Steven', 'Walker');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('2004-06-28 ', 'natalie@gmail.com', 'Natalie', 'Young');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('1996-08-22 ', 'chris@gmail.com', 'Chris', 'Hall');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('1989-12-31 ', 'jessica@gmail.com', 'Jessica', 'Garcia');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('2003-02-15 ', 'brian@gmail.com', 'Brian', 'Thompson');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('1994-10-07 ', 'michelle@gmail.com', 'Michelle', 'Adams');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('2002-01-29 ', 'andrew@gmail.com', 'Andrew', 'Cook');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('1991-06-03 ', 'linda@gmail.com', 'Linda', 'Parker');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('2001-04-10 ', 'jason@gmail.com', 'Jason', 'Ross');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('1984-09-14 ', 'ashley@gmail.com', 'Ashley', 'Allen');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('2002-03-05 ', 'matthew@gmail.com', 'Matthew', 'Wright');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('1999-01-18 ', 'kimberly@gmail.com', 'Kimberly', 'Baker');
INSERT INTO users(birthday, email, first_name, last_name)
VALUES ('2003-08-07 ', 'daniel@gmail.com', 'Daniel', 'Gonzalez');
